### ISSUE TITLE
Small bug in getting the current time

### ISSUE THREAD

**Issue by mikkosyrjasuo** [lhmarsden/NetCDF-CF_workshops#1]
https://github.com/lhmarsden/NetCDF-CF_workshops/blob/74c3e3a5bcb9f7fee39b33986df4fce63dc9d7a2/Python_workshop_materials/create_netcdf_depth_profile.py#L33

Hi Luke,

I think you may have a small bug in your example script, which results in using the local rather than UTC time in `date_created` attribute. A small change would make it work as intended regardless of the computer's timezone settings, wouldn't it?

`dtnow = dt.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")`

Cheers,

Mikko

(nice and useful youtube video describing the details of the script, btw.)

**Comment by lhmarsden** [comment]
Thanks for spotting that, Mikko. I will correct it in this and the other scripts.

Cheers

Luke
